### PR TITLE
Rendering arrows widget

### PR DESCRIPTION
**Pull request by prybicki**
See doc on ArrowsWidget class

---
This change is [Reviewable](https://reviewable.io/reviews/codilime/veles/413)

### CODE REVIEW

**Comment by chivay** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[include/ui/disasm/arrows.h, line 45 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75F4vvfEOn5P8vXH61:-L75F4vvfEOn5P8vXH62:b-sh2r76) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L45)):*
> ```objc
>  * As input (updateArrows) it takes row attach points and vector of Arrow
>  * objects.
>  * Attach points pixel-level heights where arrows will originate or terminate.
> ```

`Attach points` are?

---

*[include/ui/disasm/arrows.h, line 65 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75GuSC2QEzJh74P5Pz:-L75GuSC2QEzJh74P5Q-:bms56n5) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L65)):*
> ```objc
>   Q_OBJECT
> 
>   const unsigned ARROWHEAD_WIDTH = 10;
> ```

Not really a fan of  `unsigned` stuff.
Google Style Guide recommends using ints, hovewer uints are present in our codebase.
summon @mkow ?

---

*[include/ui/disasm/arrows.h, line 68 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74TNRr93VK_CNdkEj4:-L74TNRr93VK_CNdkEj5:b-sm0mh3) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L68)):*
> ```objc
>   const unsigned ARROWHEAD_HEIGHT = 10;
>   const unsigned DEFAULT_WIDTH = 200;
>   const unsigned MIN_LEVELS = 8;
> ```

All of these can be static

---

*[include/ui/disasm/arrows.h, line 73 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74T7DkquhZUBxsi5pM:-L74T7DkquhZUBxsi5pN:b-jq0ek3) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L73)):*
> ```objc
>   unsigned height_ = 0;
>   unsigned levels = MIN_LEVELS;
>   unsigned points_per_level;
> ```

Missing `_` in member variable names

---

*[include/ui/disasm/arrows.h, line 76 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74TdLpAhIHg39wI7cW:-L74TdLpAhIHg39wI7cX:b-7ropln) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L76)):*
> ```objc
> 
>   std::vector<unsigned> row_attach_points;
>   std::vector<Arrow> arrows;
> ```

ditto

---

*[include/ui/disasm/arrows.h, line 78 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74LvOHgchlf6yHSr6K:-L74LvOHgchlf6yHSr6L:bxnxgs3) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L78)):*
> ```objc
>   std::vector<Arrow> arrows;
> 
>   void paintSingleArrow(Arrow& arrow, QPainter& painter);
> ```

Don't use non-const references

---

*[include/ui/disasm/arrows.h, line 80 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74ToVC9fDA0lOZoc8v:-L74ToVC9fDA0lOZoc8w:bd4oijw) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L80)):*
> ```objc
>   void paintSingleArrow(Arrow& arrow, QPainter& painter);
> 
>  public:
> ```

Public class members should be declared above private ones.

---

*[src/ui/disasm/arrows.cc, line 53 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75Ivn_xrbrph2N3wyU:-L75Ivna9ax81lj0NM7Y:b-3y7idn) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/arrows.cc#L53)):*
> ```cpp
>   painter.fillRect(event->rect(), palette().color(QPalette::AlternateBase));
> 
>   for (auto& arrow : arrows) {
> ```

It can be made const

---

*[src/ui/disasm/arrows.cc, line 113 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75LM1U8qGyu-tyOzfM:-L75LM1U8qGyu-tyOzfN:bka357i) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/arrows.cc#L113)):*
> ```cpp
>                                       end_point.y() - ARROWHEAD_HEIGHT / 2)};
> 
>   painter.drawConvexPolygon(arrowhead_points, 3);
> ```

Using `drawConvexPolygon` seems like an overkill. Maybe there's some simpler way.

---

*[src/ui/disasm/widget.cc, line 147 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74S1_1ZHdkXHSatt1o:-L74S1_1ZHdkXHSatt1p:bx2z1dq) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/widget.cc#L147)):*
> ```cpp
>   }
> 
>   // @todo(zpp) row_attach_points should be updated when toggling chunk
> ```

`@todo` -> `TODO`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/413)*

**Comment by prybicki** [comment]
Review status: 1 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[include/ui/disasm/arrows.h, line 45 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75F4vvfEOn5P8vXH61:-L7ZW4YNSJf1UN-V_3ro:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L45)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

`Attach points` are?
</blockquote></details>

Done.

---

*[include/ui/disasm/arrows.h, line 65 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75GuSC2QEzJh74P5Pz:-L7ZPxatT1zqG9nEwkrl:b-5i3ar1) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L65)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Not really a fan of  `unsigned` stuff.
Google Style Guide recommends using ints, hovewer uints are present in our codebase.
summon @mkow ?
</blockquote></details>

Did read. Corrected.

---

*[include/ui/disasm/arrows.h, line 68 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74TNRr93VK_CNdkEj4:-L7ZW5hIePklT2FpEN2c:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L68)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

All of these can be static
</blockquote></details>

Done.

---

*[include/ui/disasm/arrows.h, line 73 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74T7DkquhZUBxsi5pM:-L7ZW6nbon_FbGE2efdO:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L73)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Missing `_` in member variable names
</blockquote></details>

Done.

---

*[include/ui/disasm/arrows.h, line 76 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74TdLpAhIHg39wI7cW:-L7ZW89cwlaYT17GCLSN:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L76)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[include/ui/disasm/arrows.h, line 77 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L7ZTMfypFbchkf7kz1J:-L7ZTMfypFbchkf7kz1K:b-7f4is) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L77)):*
>   ArrowsWidget(QWidget* parent);
>  
>   void updateArrows(std::vector<unsigned> row_attach_points,
>  
>  
>   painter.fillRect(event->rect(), palette().color(QPalette::AlternateBase));
>  
>   for (auto& arrow : arrows) {

---

*[include/ui/disasm/arrows.h, line 78 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74LvOHgchlf6yHSr6K:-L7ZTfSOwJXc1bQXHUGR:b-31nqn3) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L78)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Don't use non-const references
</blockquote></details>

Arrow will be const, QPainter must remain non-const as drawing are non-const methods.

---

*[include/ui/disasm/arrows.h, line 80 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74ToVC9fDA0lOZoc8v:-L7ZW96NVG4VGh3xVYxP:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L80)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Public class members should be declared above private ones.
</blockquote></details>

Done.

---

*[src/ui/disasm/arrows.cc, line 53 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75Ivn_xrbrph2N3wyU:-L7ZWC6jeORcN28B3rYP:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/arrows.cc#L53)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

It can be made const
</blockquote></details>

Done.

---

*[src/ui/disasm/arrows.cc, line 113 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75LM1U8qGyu-tyOzfM:-L7ZUkeMabN7nezrW-Vz:b-4v8zue) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/arrows.cc#L113)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Using `drawConvexPolygon` seems like an overkill. Maybe there's some simpler way.
</blockquote></details>

`QPainter::drawTriangle` does not exist.

---

*[src/ui/disasm/widget.cc, line 147 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74S1_1ZHdkXHSatt1o:-L7ZWFktxWofzBWM4flf:b-896fix) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/widget.cc#L147)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

`@todo` -> `TODO`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/413)*

**Comment by chivay** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/ui/disasm/arrows.h, line 77 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L7ZTMfypFbchkf7kz1J:-L7ZhkbNoKyutPW1u367:b3kre) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L77)):*
<details><summary><i>Previously, prybicki wrote…</i></summary><blockquote>

>   ArrowsWidget(QWidget* parent);
>  
>   void updateArrows(std::vector<unsigned> row_attach_points,
>  
>  
>   painter.fillRect(event->rect(), palette().color(QPalette::AlternateBase));
>  
>   for (auto& arrow : arrows) {

</blockquote></details>

?

---

*[include/ui/disasm/arrows.h, line 78 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L74LvOHgchlf6yHSr6K:-L7ZhmXk_MuoLqNBY1nk:bwv4vdb) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/include/ui/disasm/arrows.h#L78)):*
<details><summary><i>Previously, prybicki wrote…</i></summary><blockquote>

Arrow will be const, QPainter must remain non-const as drawing are non-const methods.
</blockquote></details>

In this case, a pointer should be used.

---

*[src/ui/disasm/arrows.cc, line 113 at r1](https://reviewable.io:443/reviews/codilime/veles/413#-L75LM1U8qGyu-tyOzfM:-L7Zj9vSppuzIuHA5r5V:b-bshh) ([raw file](https://github.com/codilime/veles/blob/92ffe40ba60fa8350f74868fa4e5b87f23f9831e/src/ui/disasm/arrows.cc#L113)):*
<details><summary><i>Previously, prybicki wrote…</i></summary><blockquote>

`QPainter::drawTriangle` does not exist.
</blockquote></details>

`QPainterPath` could be used instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/413)*

**Comment by chivay** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/413#-:-L7_TSlexnrgXTrOKoCS:bnfp4nl)*

**Pull request merged**
