### PR TITLE
CMake simplifications + LLVM/CMake/Ubuntu versions update

### PR DESCRIPTION
**Pull request by mkow**
This change will be probably easier to review by looking at every commit separately.

---
This change is [Reviewable](https://reviewable.io/reviews/codilime/veles/425)

### CODE REVIEW

**Comment by koriakin** [comment]
*[CMakeLists.txt, line 452 at r1](https://reviewable.io/reviews/codilime/veles/425#-LBqPJRX8SFq9vh8fPHM:-LBqPJRX8SFq9vh8fPHN:bpwztjh) ([raw file](https://github.com/codilime/veles/blob/43fe9b9a28ec68e79620551c33fc1fadd0fdb06d/CMakeLists.txt#L452)):*
> ```
> ·
> ```
?

---


*Comments from [Reviewable](https://reviewable.io/reviews/codilime/veles/425)*

**Comment by koriakin** [comment]
Reviewed 47 of 47 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/codilime/veles/425)*

**Comment by mkow** [comment]
Review status: 46 of 47 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 452 at r1](https://reviewable.io/reviews/codilime/veles/425#-LBqPJRX8SFq9vh8fPHM:-LC3KXht5udlz2whPmV3:b-886gsx) ([raw file](https://github.com/codilime/veles/blob/43fe9b9a28ec68e79620551c33fc1fadd0fdb06d/CMakeLists.txt#L452)):*
<details><summary><i>Previously, koriakin (Marcin Kościelnicki) wrote…</i></summary><blockquote>

> ```
> ·
> ```
?
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/codilime/veles/425)*

**Comment by koriakin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/codilime/veles/425#-:-LC3NIgN6Iu8u-ekGO73:bnfp4nl)*

**Pull request merged**
