### PR TITLE
Single active dock widget in the application.

### PR DESCRIPTION
**Pull request by jacek-izykowski**

### CODE REVIEW

**Comment by altran01** [comment]
When I tried running this branch it fails completely when opening file.
`abort() has been called`
on line L930 in dockwidget.cc.

**Comment by jacek-izykowski** [comment]
@altran01 After last fixes I couldn't reproduce this issue. Unfortunately it doesn't prove anything as it has never happened on my Ubuntu.

**Comment by altran01** [comment]
On Ubuntu 1{4,6}.04 it now works fine for me.
On Windows 10 it still crashes - the easiest one to reproduce is during closing the application - it crashes on closing with one of following stack-traces:
` 	Qt5Widgetsd.dll!0000000069057fb0()	Unknown
 	Qt5Widgetsd.dll!00000000690093ae()	Unknown
 	Qt5Widgetsd.dll!0000000069003f49()	Unknown
 	Qt5Widgetsd.dll!00000000691e4392()	Unknown
	veles.exe!veles::ui::DockWidget::~DockWidget() Line 97	C++
 	veles.exe!veles::ui::DockWidget::scalar deleting destructor'(unsigned int)	C++
 	Qt5Cored.dll!0000000068855346()	Unknown
 	Qt5Widgetsd.dll!00000000690041ec()	Unknown
 	Qt5Widgetsd.dll!0000000069235b52()	Unknown
 	veles.exe!veles::ui::MainWindowWithDetachableDockWidgets::~MainWindowWithDetachableDockWidgets() Line 688	C++
 	veles.exe!veles::ui::VelesMainWindow::~VelesMainWindow()	C++
 	veles.exe!veles::ui::VelesMainWindow::scalar deleting destructor'(unsigned int)	C++
 	Qt5Cored.dll!0000000068856cfa()	Unknown
 	Qt5Cored.dll!000000006884f668()	Unknown
 	Qt5Widgetsd.dll!0000000069011cf2()	Unknown
 	Qt5Widgetsd.dll!00000000692380b1()	Unknown
 	veles.exe!veles::ui::MainWindowWithDetachableDockWidgets::event(QEvent * event) Line 1204	C++`

or

`    Qt5Widgetsd.dll!0000000069057fb0()	Unknown
 	Qt5Widgetsd.dll!00000000690093ae()	Unknown
 	Qt5Widgetsd.dll!0000000069003f49()	Unknown
 	Qt5Widgetsd.dll!00000000692a4e22()	Unknown
 	veles.exe!QRubberBand::scalar deleting destructor'(unsigned int)	C++
 	Qt5Cored.dll!0000000068855346()	Unknown
 	Qt5Widgetsd.dll!00000000690041ec()	Unknown
 	Qt5Widgetsd.dll!0000000069235b52()	Unknown
	veles.exe!veles::ui::MainWindowWithDetachableDockWidgets::~MainWindowWithDetachableDockWidgets() Line 688	C++
 	veles.exe!veles::ui::VelesMainWindow::~VelesMainWindow()	C++
 	veles.exe!veles::ui::VelesMainWindow::scalar deleting destructor'(unsigned int)	C++
 	Qt5Cored.dll!0000000068856cfa()	Unknown
 	Qt5Cored.dll!000000006884f668()	Unknown
 	Qt5Widgetsd.dll!0000000069011cf2()	Unknown
 	Qt5Widgetsd.dll!00000000692380b1()	Unknown
 	veles.exe!veles::ui::MainWindowWithDetachableDockWidgets::event(QEvent * event) Line 1204	C++`

However it sometimes also crashes on closing tabs with not very helpful stack-trace:
` 	Qt5Widgetsd.dll!0000000068f88e3c()	Unknown
 	Qt5Widgetsd.dll!0000000068f99d99()	Unknown
 	Qt5Widgetsd.dll!0000000068f90a13()	Unknown
 	Qt5Widgetsd.dll!0000000069020111()	Unknown
 	Qt5Widgetsd.dll!000000006900b497()	Unknown
 	Qt5Widgetsd.dll!000000006900b6db()	Unknown
 	Qt5Widgetsd.dll!00000000692c41f0()	Unknown
 	Qt5Widgetsd.dll!00000000691f4fdd()	Unknown
 	Qt5Widgetsd.dll!00000000691f5158()	Unknown
 	Qt5Widgetsd.dll!00000000691ee3c9()	Unknown
 	Qt5Widgetsd.dll!00000000691edb7d()	Unknown
 	Qt5Widgetsd.dll!00000000691ee2bb()	Unknown
 	Qt5Widgetsd.dll!00000000691f7be8()	Unknown
 	Qt5Widgetsd.dll!000000006923b2b6()	Unknown
 	Qt5Widgetsd.dll!000000006923fa59()	Unknown
 	Qt5Widgetsd.dll!0000000068fea5f6()	Unknown
 	Qt5Widgetsd.dll!0000000068fe9958()	Unknown
 	Qt5Widgetsd.dll!0000000068feb049()	Unknown
 	Qt5Widgetsd.dll!0000000068fa5e5e()	Unknown
 	Qt5Widgetsd.dll!0000000068fa34c9()	Unknown
 	Qt5Cored.dll!00000000687f78c6()	Unknown
 	Qt5Cored.dll!00000000688027f2()	Unknown
 	Qt5Cored.dll!00000000687f9112()	Unknown
 	Qt5Cored.dll!00000000688b180a()	Unknown
 	qwindowsd.dll!00007ff97574c204()	Unknown
 	Qt5Cored.dll!00000000688af521()	Unknown
 	user32.dll!00007ff9aaec1c24()	Unknown
 	user32.dll!00007ff9aaec156c()	Unknown
 	Qt5Cored.dll!00000000688aff2b()	Unknown
 	qwindowsd.dll!00007ff97574c1c4()	Unknown
 	Qt5Cored.dll!00000000687f24e8()	Unknown
 	Qt5Cored.dll!00000000687f272e()	Unknown
 	Qt5Cored.dll!00000000687f55ff()	Unknown
 	Qt5Guid.dll!00007ff9692e3208()	Unknown
 	Qt5Widgetsd.dll!0000000068fa021a()	Unknown
	veles.exe!main(int argc, char * * argv) Line 112	C++`

**Comment by jacek-izykowski** [comment]
@altran Not anymore.

**Comment by altran01** [comment]
Ok lets start.
2 "UX" comments - after starting Veles no dock has active dock look, and the same is sometimes true after closing dock which was active(dock that should be active is marked as active for a second and then it isn't) - while at both of those situations there undoubtedly is an active dock.
Also for some reason this mechanism is surprisingly slow - on debug it is really slow.

It now once again on Ubuntu (both 16.04 VM and 14.04 physical machine) it crashes when opening any file with following stack-trace:

>#0  0x00007ffff55284a3 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000054af8c in veles::ui::DockWidget::getParentDockWidget (obj=0xf88740) at /home/jacek/workspace/veles/src/ui/dockwidget.cc:124
#2  0x0000000000550a08 in veles::ui::MainWindowWithDetachableDockWidgets::focusChanged (this=0xd45dc0, old=0xf82ce0, now=0xf88740) at /home/jacek/workspace/veles/src/ui/dockwidget.cc:1188
#3  0x0000000000556f37 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QWidget*, QWidget*>, void, void (veles::ui::MainWindowWithDetachableDockWidgets::*)(QWidget*, QWidget*)>::call (f=
    (void (veles::ui::MainWindowWithDetachableDockWidgets::*)(veles::ui::MainWindowWithDetachableDockWidgets * const, QWidget *, QWidget *)) 0x55099c <veles::ui::MainWindowWithDetachableDockWidgets::focusChanged(QWidget*, QWidget*)>, o=0xd45dc0, arg=0x10b5d90) at /home/jacek/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h:507
#4  0x0000000000555fd2 in QtPrivate::FunctionPointer<void (veles::ui::MainWindowWithDetachableDockWidgets::*)(QWidget*, QWidget*)>::call<QtPrivate::List<QWidget*, QWidget*>, void> (f=
    (void (veles::ui::MainWindowWithDetachableDockWidgets::*)(veles::ui::MainWindowWithDetachableDockWidgets * const, QWidget *, QWidget *)) 0x55099c <veles::ui::MainWindowWithDetachableDockWidgets::focusChanged(QWidget*, QWidget*)>, o=0xd45dc0, arg=0x10b5d90) at /home/jacek/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h:526
#5  0x0000000000554c31 in QtPrivate::QSlotObject<void (veles::ui::MainWindowWithDetachableDockWidgets::*)(QWidget*, QWidget*), QtPrivate::List<QWidget*, QWidget*>, void>::impl (which=1, this_=0xb6ec10, 
    r=0xd45dc0, a=0x10b5d90, ret=0x0) at /home/jacek/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h:149
#6  0x00007ffff5c8a61a in QObject::event(QEvent*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#7  0x00007ffff6a4cd1b in QWidget::event(QEvent*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.so.5
#8  0x00007ffff6b4564b in QMainWindow::event(QEvent*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.so.5
#9  0x0000000000550c1f in veles::ui::MainWindowWithDetachableDockWidgets::event (this=0xd45dc0, event=0x1085dc0) at /home/jacek/workspace/veles/src/ui/dockwidget.cc:1224
#10 0x00007ffff6a0752c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.so.5
#11 0x00007ffff6a0e220 in QApplication::notify(QObject*, QEvent*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.so.5
#12 0x00007ffff5c61ae0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#13 0x00007ffff5c6451b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#14 0x00007ffff5caec53 in ?? () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#15 0x00007ffff1e72e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff1e73048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff1e730ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff5caf047 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#19 0x00007ffff5c5fdca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#20 0x00007ffff5c67bad in QCoreApplication::exec() () from /home/jacek/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5
#21 0x000000000053dcde in main (argc=1, argv=0x7fffffffd788) at /home/jacek/workspace/veles/src/ui/main.cc:112

On Windows I've encountered following assertion fails when moving active dock around to other windows (although I don't know if they are directly caused by this changes or just made more plausible):

> ASSERT: "index >= 0" in file widgets\qtabbar.cpp, line 697
ASSERT failure in QList<T>::operator[]: "index out of range", file c:\users\qt\work\qt\qtbase\include\qtcore\../../src/corelib/tools/qlist.h, line 545

They are triggered in `MainWindowWithDetachableDockWidgets::updateActiveDockWidget` when it calls `QApplication::processEvents();`

**Pull request merged**
