### PR TITLE
Disasm::toggleColumns

### PR DESCRIPTION
**Pull request by malpunek**
This change is [Reviewable](https://reviewable.io/reviews/codilime/veles/409)

### CODE REVIEW

**Comment by chivay** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[include/ui/disasm/row.h, line 41 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RxcTSnhG5YaRDfUsk:-L6RxcTSnhG5YaRDfUsl:bt2vtx5) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/row.h#L41)):*
> ```objc
>   void setEntry(const EntryField* entry);
>   enum ColumnName { Address, Chunks, Comments };
>   void toggleColumn(ColumnName columnName);
> ```

`columnName` -> `column_name`

---

*[include/ui/disasm/tab.h, line 19 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6Rx4DYU0beDp6HeQH3:-L6Rx4DYU0beDp6HeQH4:b-knne2y) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/tab.h#L19)):*
> ```objc
> 
> #pragma once
> #include <QToolBar>
> ```

Empty line after `#pragma once`

---

*[include/ui/disasm/tab.h, line 38 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RxjgIHlApCZh_ubxP:-L6RxjgIHlApCZh_ubxQ:bef2dtb) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/tab.h#L38)):*
> ```objc
>  private:
>   void createToolbars();
>   QToolBar* tool_bar;
> ```

`tool_bar` -> `tool_bar_`
Maybe empty line after `void createToolbar(s);` ?

---

*[include/ui/disasm/widget.h, line 46 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RyA29y1EAKrQ8KLBm:-L6RyA29y1EAKrQ8KLBn:bt2vtx5) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/widget.h#L46)):*
> ```objc
>  public slots:
>   void getWindow();
>   void toggleColumn(Row::ColumnName columnName);
> ```

`columnName` -> `column_name`

---

*[src/ui/hexeditwidget.cc, line 263 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RwGmgsISwLzSeyoGf:-L6RwGmgsISwLzSeyoGg:bbxg8jr) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/src/ui/hexeditwidget.cc#L263)):*
> ```cpp
>   parser_tool_button->setToolTip(tr("Parser"));
>   parser_tool_button->setAutoRaise(true);
> ```

What happened here?

---

*[src/ui/disasm/row.cc, line 67 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RyEmDKODBdMvMRD9b:-L6RyEmDKODBdMvMRD9c:bt2vtx5) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/src/ui/disasm/row.cc#L67)):*
> ```cpp
> void Row::setEntry(const EntryField* entry) {}
> 
> void Row::toggleColumn(Row::ColumnName columnName) {
> ```

`columnName` -> `column_name`

---

*[src/ui/disasm/tab.cc, line 19 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RvqQxQ9Dir2xYlkux:-L6RvqQxQ9Dir2xYlkuy:bg759bs) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/src/ui/disasm/tab.cc#L19)):*
> ```cpp
> 
> #include "ui/disasm/tab.h"
> #include <QToolButton>
> ```

Add empty line after `#include "ui/disasm/tab.h"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/409)*

**Comment by malpunek** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[include/ui/disasm/row.h, line 41 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RxcTSnhG5YaRDfUsk:-L7-W-6KDdQjJpgioQwH:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/row.h#L41)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

`columnName` -> `column_name`
</blockquote></details>

Done.

---

*[include/ui/disasm/tab.h, line 19 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6Rx4DYU0beDp6HeQH3:-L7-W2vap9q1HuoVPxHP:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/tab.h#L19)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Empty line after `#pragma once`
</blockquote></details>

Done.

---

*[src/ui/hexeditwidget.cc, line 263 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RwGmgsISwLzSeyoGf:-L7-WgOIej12pf8S5-gj:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/src/ui/hexeditwidget.cc#L263)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

What happened here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/409)*

**Comment by malpunek** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[include/ui/disasm/tab.h, line 38 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RxjgIHlApCZh_ubxP:-L7-XOT5P51j_u5tQ7xt:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/tab.h#L38)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

`tool_bar` -> `tool_bar_`
Maybe empty line after `void createToolbar(s);` ?
</blockquote></details>

Done.

---

*[include/ui/disasm/widget.h, line 46 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RyA29y1EAKrQ8KLBm:-L7-XLyecPmjcuV-DfX4:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/include/ui/disasm/widget.h#L46)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

`columnName` -> `column_name`
</blockquote></details>

Done.

---

*[src/ui/disasm/row.cc, line 67 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RyEmDKODBdMvMRD9b:-L7-XJNYyP99EvpjgfpG:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/src/ui/disasm/row.cc#L67)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

`columnName` -> `column_name`
</blockquote></details>

Done.

---

*[src/ui/disasm/tab.cc, line 19 at r2](https://reviewable.io:443/reviews/codilime/veles/409#-L6RvqQxQ9Dir2xYlkux:-L7-XGiBQhFgKhe5FXvM:b-896fix) ([raw file](https://github.com/codilime/veles/blob/cd8bfdcb2007e67913694595133408de51fca1ef/src/ui/disasm/tab.cc#L19)):*
<details><summary><i>Previously, chivay (Hubert Jasudowicz) wrote…</i></summary><blockquote>

Add empty line after `#include "ui/disasm/tab.h"`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/409)*

**Comment by chivay** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/codilime/veles/409)*

**Pull request merged**
